name: CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    name: ${{ matrix.friendlyName }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [15.x]
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            friendlyName: Windows
          - os: macos-latest
            friendlyName: macOS
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      # This step can be removed as soon as official Windows arm64 builds are published:
      # https://github.com/nodejs/build/issues/2450#issuecomment-705853342
      - run: |
          $NodeVersion = (node --version) -replace '^.'
          $NodeFallbackVersion = "15.8.0"
          & .\script\download-node-lib-win-arm64.ps1 $NodeVersion $NodeFallbackVersion
        if: ${{ matrix.os == 'windows-latest' }}
        name: Install Windows arm64 node.lib

      - name: Install and build dependencies
        run: yarn
      - name: Lint
        run: yarn check-prettier
      - name: Build
        run: yarn build
      - name: Prebuild x64
        run: npm run prebuild-napi-x64
      - name: Prebuild arm64
        run: npm run prebuild-napi-arm64
      - name: Publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: yarn upload
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
